<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\PermissionRegistrar;
use Illuminate\Support\Str;

class ShieldSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Reset cached roles and permissions
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        // Ensure roles exist
        $roles = ['super_admin', 'editor', 'analyst', 'viewer'];
        foreach ($roles as $role) {
            Role::firstOrCreate(['name' => $role, 'guard_name' => 'web']);
        }

        $viewerRole = Role::findByName('viewer');
        $editorRole = Role::findByName('editor');
        $analystRole = Role::findByName('analyst');
        
        // Fetch all permissions (generated by shield:generate)
        $permissions = Permission::all();

        foreach ($permissions as $permission) {
            $name = $permission->name;
            $lowerName = Str::lower($name);

            // 1. Skip System Resources (Users, Roles, Permissions) for non-super-admins
            // Note: permissions are like View:User, so 'user' check works.
            if (Str::contains($lowerName, ['user', 'role', 'permission'])) {
                continue;
            }

            // 2. Analytics Permissions
            // Permissions: View:AnalyticsEvent, View:AnalyticsRequest
            if (Str::contains($lowerName, 'analytics')) {
                // Analyst gets access to analytics
                if (Str::startsWith($lowerName, 'view')) {
                    $analystRole->givePermissionTo($permission);
                }
                continue;
            }

            // 3. Business Resources (Products, Brands, etc.)
            
            // View Access (View:Product, ViewAny:Product)
            if (Str::startsWith($lowerName, ['view'])) {
                $viewerRole->givePermissionTo($permission);
                $analystRole->givePermissionTo($permission);
                $editorRole->givePermissionTo($permission);
            }

            // Write Access (Create:Product, Update:Product, etc.)
            if (Str::startsWith($lowerName, ['create', 'update', 'delete', 'restore', 'reorder', 'replicate', 'force'])) {
                $editorRole->givePermissionTo($permission);
            }
        }
    }
}
